### PR TITLE
Allow systray support for gnome

### PR DESCRIPTION
**Pull request by wberrier**
This patch can probably be sent upstream...

This is to address #6

### CODE REVIEW

**Comment by penyuan** [comment]
> Build [23812 successful](https://flathub.org/builds/#/builders/32/builds/23812)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/22876/org.davmail.DavMail.flatpakref
> ```

Thanks, I am happy to test this. But is there a way to revert to the "normal" build from Flathub once I finish testing? How do I do that?

**Comment by wberrier** [comment]
To test:

* uninstall davmail (to make sure you are really running the test version.  no settings are lost)
* install via the above command
* uninstall the test davmail
* reinstall the version from flathub

**Comment by penyuan** [comment]
Thank you @wberrier for the clear instructions, I have installed and test this test build. Here are my findings:

1. DavMail now starts directly into the system tray icon and is accessible from the icon! :+1:  This works fine in Gnome Wayland mode, *but* in Xorg mode the tray icon is completely invisible! I can click on and interact with the icon, but it is not visible...
2. In Xorg mode, there is a strange, tiny "window" that shows up even though I can't interact with it. Here is a GIF screen shot of me hovering my mouse cursor over that window in Gnome's window overview mode:



What does this mean???

I will keep this test build installed for now (it is functioning normally) to help test, just let me know what to do!

**Comment by wberrier** [comment]
I tried this out on X11 gnome3 also, I found that the icon didn't appear, but I could still right mouse click on it... ?

It may just be an issue of how the icon is drawn... not sure yet...

**Comment by penyuan** [comment]
> but I could still right mouse click on it... ?

Then we can both reproduce the same issue, that's good!

Do you also see the issue in my previous comment about a strange, tiny "window" that shows up even though I can't interact with it? (see above comment for a GIF of what it looks like)

**Comment by wberrier** [comment]
> Do you also see the issue in my previous comment about a strange, tiny "window" that shows up even though I can't interact with it? (see above comment for a GIF of what it looks like)

Ah, I didn't check for that, but I'm assuming I would also see this, and I think it's related to an issue I reported with #6 

> * even when running in the sys-tray, alt-tab still lists davmail for the workspace it was started on

Question is, how many of these items should we try to fix before merging this in?

**Comment by penyuan** [comment]
Thank you for your help @wberrier! :clap:

> Question is, how many of these items should we try to fix before merging this in?

Since I'm just a user I don't know what the best practice is (if there is one). I'm just eager and happy to help diagnose the problem to help the developers find a fix. Whether that's in this pull request or another I'm game either way!

**Comment by penyuan** [comment]
Hi!

Just touching base to see if there is still anything I can help test before this pull request can be merged?

I've been running [build 23812](https://github.com/flathub/org.davmail.DavMail/pull/9#issuecomment-659051241) by @flathubbot above since July 16 with no problems in functionality (albeit with the funny tiny window thing I mentioned in [this comment](https://github.com/flathub/org.davmail.DavMail/pull/9#issuecomment-659649238) above, but I don't think that's a blocker for this pull request).

If there are no major problems I suggest this pull request be merged.

Many thanks to @wberrier!

**Pull request merged**
